### ISSUE TITLE
amsterdam-schema-tools | python requirement is >= 3.7

### ISSUE THREAD

**Issue by AbinayaSandhiyaM** [Amsterdam/schema-tools#176]
Hi,

We have tried to install amsterdam-schema-tools==0.22.0 via pip with python version "3.6.8 [ which is the default version of python in RHEL7]

Below is the issue

[root@cli-automation-test linsee_packaging_automation_bpk]$ pip3 install amsterdam-schema-tools==0.22.0
ERROR: Could not find a version that satisfies the requirement amsterdam-schema-tools==0.22.0 (from versions: 0.0.2, 0.0.3)
ERROR: No matching distribution found for amsterdam-schema-tools==0.22.0
[root@cli-automation-test linsee_packaging_automation_bpk]$

we understand that this issue is due to lower version of python from site https://pypi.org/project/amsterdam-schema-tools/
[amsterdam requires >= 3.7 python version ]

also there are dependencies for amsterdam that required >= 3.8 version of python.

As default version of python is something 3.6 on RedHAT 7, is that mean these module required latest version of python or how it is.

could you please let us know the details / documentation for the better understanding.

Thanks!

**Comment by jjmurre** [comment]
I am afraid the python >= 3.8 is really a hard requirement. The reason is that we use assignment expressions (`:=` aka. walrus operator) throughout the code and this is only possible with python >= 3.8

**Comment by AbinayaSandhiyaM** [comment]
Hello Jan,

thanks for your quick response.

So you mean the components like amsterdam-schema-tools totally depends with higher version of python or my understand is wrong here?

**Comment by lbam** [comment]
Yes, this package requires Python 3.8.
